version: '3.5'

services:

  ves:
    container_name: ves
    image: nexus3.onap.org:10001/onap/org.onap.dcaegen2.collectors.ves.vescollector:1.11.0 #latest
    environment:
      - DMAAPHOST="192.168.20.17:3904"
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - nf-simulator-network

  onap-dmaap:
    container_name: dmaap
    image: dmaap-simulator
    ports:
      - "3904:3904"
    networks:
      - nf-simulator-network

#
# external network
networks:
  nf-simulator-network:
    external:
      name: nf-simulator-network
